# version of docker-compose syntax
version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - production_static_data:/vol/web
    restart: always


volumes:
  production_static_data:
                                      
