# Generated by Django 3.2 on 2021-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('client_code', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='bank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
