# Generated by Django 3.2 on 2021-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgermodel',
            old_name='status',
            new_name='type_status',
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='bene_account_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='bene_account_number',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='bene_ifsc',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='trans_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='bank',
            field=models.IntegerField(),
        ),
    ]
