# Generated by Django 3.2 on 2021-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210612_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('charge_percentage_or_fix', models.IntegerField()),
                ('charge_amount_percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoleFeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('feature', models.IntegerField()),
                ('create', models.BooleanField()),
                ('read', models.BooleanField()),
                ('update', models.BooleanField()),
                ('delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='client_password',
            field=models.CharField(default='xxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='client_username',
            field=models.CharField(default='xxxxxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='is_merchant',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='is_payout',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='role',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='charge',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='mode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='request_header',
            field=models.CharField(default='{}', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='amount',
            field=models.FloatField(),
        ),
    ]
