# Generated by Django 3.2 on 2021-06-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20210613_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolefeaturemodel',
            name='create',
        ),
        migrations.RemoveField(
            model_name='rolefeaturemodel',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='rolefeaturemodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='rolefeaturemodel',
            name='update',
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='create',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='delete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='read',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='update',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
