# Generated by Django 3.2 on 2021-06-13 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_ledgermodel_trans_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
