# Generated by Django 3.2 on 2021-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_ledgermodel_van'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_status',
            field=models.CharField(max_length=100),
        ),
    ]
