# Generated by Django 3.2 on 2021-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_ledgermodel_trans_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpHittingRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=300)),
                ('hitting_time', models.DateTimeField()),
                ('ip_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IpWhiteListedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('client_code', models.CharField(max_length=300)),
                ('ip_address', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
