# Generated by Django 3.2 on 2021-07-15 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20210714_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmodel',
            name='is_charge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantmodel',
            name='is_encrypt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 737704)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 737704)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 706454)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 722079)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 737704)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_by',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='deleted_by',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='updated_by',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 12, 0, 12, 737704)),
        ),
    ]
