# Generated by Django 3.2 on 2021-06-22 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20210614_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 255150)),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 302039)),
        ),
        migrations.AddField(
            model_name='chargemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='chargemodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 239518)),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 286409)),
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 318383)),
        ),
        migrations.AddField(
            model_name='ipwhitelistedmodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ipwhitelistedmodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 270779)),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 358387)),
        ),
        migrations.AddField(
            model_name='modemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='modemodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 346385)),
        ),
        migrations.AddField(
            model_name='rolefeaturemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='rolefeaturemodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 16, 55, 330380)),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
