# Generated by Django 3.2.4 on 2021-07-09 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20210709_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlabModel',
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='payout_trans_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='purpose',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 926616)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 44, 566094)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 926616), null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_amount_type',
            field=models.CharField(default='credited', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 926616)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 926616)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 933626)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 11, 24, 43, 949260)),
        ),
    ]
