# Generated by Django 3.2.4 on 2021-06-25 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20210623_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgermodel',
            name='createdBy',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='deletedBy',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='updatedBy',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 736750)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 752410)),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 721126)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 752410)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 752410)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 736750)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 767999)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 767999)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 55, 22, 752410)),
        ),
    ]
