# Generated by Django 3.2.4 on 2021-06-25 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20210625_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 203633)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 203633)),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 203633)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 203633)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 219275)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 203633)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='deletedBy',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 203633)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='updatedBy',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 219275)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 219275)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 16, 38, 26, 219275)),
        ),
    ]
