# Generated by Django 3.2 on 2021-06-27 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_auto_20210627_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 531142)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 535143)),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 529143)),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 534142)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 539142)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 532142)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 532142)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 545142)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 543142)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 14, 24, 9, 542144)),
        ),
    ]
