# Generated by Django 3.2.4 on 2021-06-28 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20210627_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 256922)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 272522)),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 256922)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 256922)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 272522)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 256922)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 256922)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 272522)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 272522)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 19, 40, 272522)),
        ),
    ]
