# Generated by Django 3.2 on 2021-06-29 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20210627_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPartnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=100)),
                ('nodal_account_number', models.CharField(max_length=300)),
                ('nodal_ifsc', models.CharField(max_length=300)),
                ('nodal_account_name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450))),
                ('deleted_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(null=True)),
                ('client', models.IntegerField()),
                ('client_code', models.CharField(max_length=60)),
                ('auth_key', models.CharField(max_length=60)),
                ('auth_iv', models.CharField(max_length=60)),
                ('bank', models.IntegerField()),
                ('client_username', models.CharField(max_length=100)),
                ('client_password', models.CharField(max_length=100)),
                ('is_payout', models.BooleanField(null=True)),
                ('is_merchant', models.BooleanField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('user', models.IntegerField()),
                ('created_by', models.CharField(max_length=300)),
                ('updated_by', models.CharField(max_length=300)),
                ('deleted_by', models.CharField(max_length=300)),
                ('is_ip_checking', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='BankModel',
        ),
        migrations.DeleteModel(
            name='ClientModel',
        ),
        migrations.RenameField(
            model_name='ipwhitelistedmodel',
            old_name='client_model',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='ledgermodel',
            old_name='client',
            new_name='merchant',
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 696229)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 38, 47, 680450)),
        ),
    ]
