# Generated by Django 3.2.4 on 2021-07-03 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_auto_20210630_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgermodel',
            name='linked_ledger_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='system_remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 881370)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 921043)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 917046)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 928081)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 910361)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_amount_type',
            field=models.CharField(default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 910361)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 942778)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 876787)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 939804)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 935770)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 55, 13, 931702)),
        ),
    ]
