# Generated by Django 3.2 on 2021-06-30 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0031_auto_20210629_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='create',
        ),
        migrations.RemoveField(
            model_name='rolemodel',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='rolemodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='rolemodel',
            name='update',
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='created_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='deleted_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='updated_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rolefeaturemodel',
            name='created_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rolefeaturemodel',
            name='deleted_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rolefeaturemodel',
            name='updated_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='created_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='deleted_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='permited_apis',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='updated_by',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 957879)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 44, 0, 963389)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
