# Generated by Django 3.2.4 on 2021-07-07 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0031_auto_20210706_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=3000)),
                ('account_number', models.CharField(max_length=400)),
                ('ifsc_code', models.CharField(max_length=500)),
                ('merchant_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 687867))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.DateTimeField(default=None, null=True)),
                ('updated_by', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='chargemodel',
            old_name='charge_amount_percentage',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='chargemodel',
            old_name='client',
            new_name='merchant_id',
        ),
        migrations.AddField(
            model_name='useractivemodel',
            name='login_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 123203)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='charge_percentage_or_fix',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 138832)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 138832)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 138832)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='linked_ledger_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='remarks',
            field=models.CharField(default='remarks', max_length=900),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='status_code',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='system_remarks',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 138832)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 123203)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 46, 48, 154456)),
        ),
    ]
