# Generated by Django 3.2 on 2021-07-03 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0034_auto_20210702_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('user_type', models.CharField(max_length=1000)),
                ('verification_token', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=1000)),
                ('otp', models.BigIntegerField()),
                ('expire_datetime', models.DateTimeField()),
                ('otp_status', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 922615))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.DateTimeField(default=None, null=True)),
                ('updated_by', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='merchantmodel',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 909614)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 914616)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 912614)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 916615)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 911614)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 911614)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 921615)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 907614)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 920615)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 918616)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 50, 917615)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 59, 51, 771600)),
        ),
    ]
