# Generated by Django 3.2 on 2021-07-05 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0036_auto_20210705_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField()),
                ('tab_token', models.CharField(max_length=300)),
                ('active_status', models.CharField(max_length=300)),
                ('login_status', models.CharField(max_length=300)),
                ('ip_address', models.CharField(max_length=300)),
                ('last_server_call_time', models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 521285))),
                ('geo_location', models.CharField(max_length=3000)),
                ('login_time', models.DateTimeField()),
                ('login_expire_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 521285))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.DateTimeField(default=None, null=True)),
                ('updated_by', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 483526)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 483526)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 18, 499149)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 22, 44, 19, 246739)),
        ),
    ]
