# Generated by Django 3.2 on 2021-07-05 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0037_auto_20210705_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivemodel',
            old_name='ip_address',
            new_name='client_ip_address',
        ),
        migrations.RemoveField(
            model_name='useractivemodel',
            name='last_server_call_time',
        ),
        migrations.AddField(
            model_name='useractivemodel',
            name='tab_token_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 887242)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 865106)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 880730)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 887242)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 880730)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 880730)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 34, 588677)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 0, 27, 33, 887242)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='login_expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
