# Generated by Django 3.2 on 2021-07-06 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0039_auto_20210706_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgermodel',
            name='linked_ledger_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='status_code',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='ledgermodel',
            name='system_remarks',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 75290)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 106539)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 90934)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 106539)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 90934)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='remarks',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 90934)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 122177)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 59664)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 106539)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 122177)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 106539)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 106539)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 42, 732644)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 13, 41, 122177)),
        ),
    ]
