name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build -t back .
    - name: Tags
      run: |
        docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
        docker tag back ${{ secrets.DOCKER_USER }}/back:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/back:latest
